### ISSUE TITLE
would you be open to a functional, data-oriented refactor?

### ISSUE THREAD

**Issue by mreinstein** [pshegde/priority-queue-v2#1]
hello! 👋 

This module seems to be really good quality in that it's tiny and has decent tests. Well done!

Would you be open to a refactor that changes the API such that it is more functional, and doesn't allocate memory at run time? To give you a sense of what this might look like:

part of heap.js:

```javascript
// creates a new heap data structure
function create (comparator, maxLength=1000) {
	const arr = new Array(maxLength)
	return { arr, length: 0, maxLength, comparator }
}

function insert (heap, item) {
	if (heap.length === heap.maxLength)
		return

	heap.arr[heap.length] = item
	heap.length++
	callHeapify(heap)
}

// ... rest of implementation would follow here
```

These changes make it more usable in games and simulations because it allocates a fixed amount of memory up front, and reduces "animation jank" due to the garbage collector reclaiming memory at run time.

Thoughts? Happy to send a PR if this is something you're open to.

Thanks for a great PQ module!

**Comment by pshegde** [comment]
Hi,
Sounds good. Please send the PR. Thanks for the feedback!

**Comment by mreinstein** [comment]
I'll work on it now! Should have it ready in the next 15 minutes.
